ext_type: "parameter  "
ext_set:
  - name: "common"
    description: "общее"
    type:
      - name: "name"
        type: "string"
        description: "имя параметра"
        help: "имя параметра"

      - name: "identifier"
        type: "string"
        description: "идентификатор"

      - name: "units"
        type: "string"
        description: "ед. измерения"

      - name: "category"
        type: "string"
        description: "категория"

      - name: "system"
        type: "string"
        description: "система"

      - name: "department"
        type: "string"
        description: "отдел"

      - name: "description"
        type: "long_string"
        description: "описание"

      - name: "path"
        type: "string"
        description: "физический адрес параметра"
        help: "номер слота, канал и т.д"

      - name: "polynomial"
        description: "коэффициенты полинома"
        dims: [ 0 ]
        type: "f64"

      - name: "approximation"
        description: "точки аппроксимации"
        dims: [ 0 ]
        type:
          - name: "x"
            type: "f64"
          - name: "y"
            type: "f64"

  - name: "ethernet_udp"
    type:
      - name: "common"
        include: "common"

      - name: "source"
        description: "источник"
        type: &address
          - name: "ip"
            type: "u32"
            description: "ip"
            representation: "ip"

          - name: "port"
            type: "i16"
            description: "порт"
            default: 4660

      - name: "destination"
        description: "порт"
        type: *address

      - name: "offset"
        type: "int"
        description: "смещение"

      - name: "type"
        type: "string"
        description: "тип/размер"
        enum: [ "i8", "i16", "i32", "i64", "f32", "f64" ]

      - name: "byte_order"
        type: "string"
        description: "порядок байт"
        enum: [ "LE" , "BE" ]

      - name: "msb"
        type: "i16"
        description: "старший разряд"
        enum: [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16 ]
        #{ 1:0, 2:1, 3:2, 4:3, 5:4, 6:5, 7:6, 8:7, 9:8, 10:9, 11:10, 12:11, 13:12, 14:13, 15:14, 16:15 }

      - name: "bit_depth"
        type: "i16"
        description: "длинна бит"
        #validator: "lambda x: 10 < x and x < 100 and x % 2 = 0"

      - name: "sign"
        type: "bool"
        description: "знак"
        enum: { есть: true, нет: false }

      - name: "scale_a1"
        type: "i32"
        description: "коэф. масштаба (a1)"

      - name: "offset_a2"
        type: "i32"
        description: "коэф. смещения (a2)"


  - name: "analog"
    type:
      - name: "common"
        include: "common"


  - name: "acceleration"
    type:
      - name: "common"
        include: "common"

      - name: "conversion_factor"
        type: "f64"
        description: "коэф. преобразования V~a"
        help: "м/c^2/в"


  - name: "velocity"
    type:
      - name: "common"
        include: "common"

      - name: "conversion_factor"
        type: "f64"
        description: "коэф. преобразования V~a"
        help: "м/c^2/в"

      - name: "length"
        type: "f64"
        description: "период интегрирования, с"


  - name: "displacement"
    type:
      - name: "common"
        include: "common"

      - name: "conversion_factor"
        type: "f64"
        description: "коэф. преобразования V~a, м/c^2/в"
        help: "м/c^2/в"

      - name: "length"
        type: "f64"
        description: "период интегрирования, c"
        help: "c"


  - name: "thermocouple_emf"  # type 3 ЭДС
    type:
      - name: "common"
        include: "common"

  - name: "thermocouple_temperature"  # type 3
    type:
      - name: "common"
        include: "common"

      - name: "thermocouple_type"
        type: "string"
        enum: { "R (ТПП)": "TP_R_TtoE", "S (ТПП)": "TP_S_TtoE", "B (ТПР)": "TP_B_TtoE", "J (ТЖК)": "TP_J_TtoE",
                "T (ТМК)": "TP_T_TtoE" , "E (ТХКн)": "TP_E_TtoE", "K (ТХА)": "TP_K_TtoE_A", "N (ТНН)": "TP_N_TtoE",
                "A-1 (ТВР)": "TP_A1_TtoE", "A-2 (ТВР)": "TP_A2_TtoE", "A-3 (ТВР)": "TP_A3_TtoE",
                "L (ТХК)": "TP_L_TtoE", "M (ТМК)": "TP_M_TtoE" }
        description: "тип термопары"


  - name: "thermistor_resistance"  # type 4
    type:
      - name: "common"
        include: "common"

  - name: "thermistor_temperature"  # type 4
    type:
      - name: "common"
        include: "common"

      - name: "thermistor_type"
        type: "u64"
        enum: { "Pt, 0.00385": 0,  "П, 0.00391": 1,  "М, 0.00428": 2,  "Н, 0.00617": 3 }
        description: "тип термопары"

      - name: "resistor_value"
        type: "f64"
        description: "R0, Ом"
        help: ""


