ext_type: "parameter  "
ext_set:
  - name: "common"
    description: "общее"
    type:
      - name: "name"
        type: "string"
        description: "имя параметра"

      - name: "identifier"
        type: "string"
        description: "идентификатор"

      - name: "units"
        type: "string"
        description: "ед. измерения"

      - name: "category"
        type: "string"
        description: "категория"

      - name: "system"
        type: "string"
        description: "система"

      - name: "department"
        type: "string"
        description: "отдел"

      - name: "description"
        type: "long_string"
        description: "описание"

      - name: "path"
        type: "string"
        description: "физический адрес параметра"

      - name: "approximation"
        description: "точки аппроксимации"
        dims: [ 0 ]
        type:
          - name: "x"
            type: "f64"
          - name: "y"
            type: "f64"

  - name: "ethernet"
    type:
      - name: "common"
        include: "common"

      - name: "source"
        description: "источник"
        type: &address
          - name: "ip"
            type: "u32"
            description: "ip"
            representation: "ip"

          - name: "port"
            type: "i16"
            description: "порт"
            default: 4660

      - name: "destination"
        description: "порт"
        type: *address

      - name: "offset"
        type: "int"
        description: "смещение"

      - name: "type"
        type: "string"
        description: "тип/размер"
        enum: [ "i8", "i16", "i32", "i64", "f32", "f64" ]

      - name: "byte_order"
        type: "string"
        description: "порядок байт"
        enum: [ "LE" , "BE" ]

      - name: "msb"
        type: "i16"
        description: "старший разряд"
        enum: [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16 ]
        #{ 1:0, 2:1, 3:2, 4:3, 5:4, 6:5, 7:6, 8:7, 9:8, 10:9, 11:10, 12:11, 13:12, 14:13, 15:14, 16:15 }

      - name: "bit_depth"
        type: "i16"
        description: "длинна бит"
        #validator: "lambda x: 10 < x and x < 100 and x % 2 = 0"

      - name: "sign"
        type: "bool"
        description: "знак"
        enum: { есть: true, нет: false }

      - name: "scale_a1"
        type: "i32"
        description: "коэф. масштаба (a1)"

      - name: "offset_a2"
        type: "i32"
        description: "коэф. смещения (a2)"

  - name: "analog"
    type:
      - name: "common"
        include: "common"